### ISSUE TITLE
No matcher proposals after "not"

### ISSUE THREAD

**Issue by jabby** [angelozerr/tern-jasmine#1]
First of all, thanks for your job. 

I use this definition in your angular-eclipse plugin and I notice a little lack in the definition. In fact autocomplete after "not" proposal should provide all matchers (toBeDefined, toBe, toBeCloseTo, toBeFalsy, toBeTruthy, toBeGreaterThan, toBeLessThan, toBeNaN, toBeNull, toBeUndefined, toContain, toEqual, toHaveBeenCalled, toHaveBeenCalledWith, toMatch, toThrow, toThrowError).

```javascript
expect("a string").not. + autocomplete should list all matchers
```
I have one more question. This tern plugin is for jasmine 1.3 or higher ?

**Comment by angelozerr** [comment]
@jabby, I have fixed the problem with `not` matcher and it should work now.

For your information  : 

 * I have created too several tests and you can see a test with `not` inside test_expect_completion.js.
 * I have created a sample tern plugin `custom_matchers.js` to show how to contribute to tern jasmine with custom matcher.
