### ISSUE TITLE
Submodule loading issue when installed as sibling to tern via npm

### ISSUE THREAD

**Issue by tomv564** [angelozerr/tern-jasmine#3]
Hi Angelo, thanks for the plugin.

I am using it through tern_for_sublime on OS-X (latest tern, node v0.12.7). 
If I drop the jasmine.js file straight into **tern_for_sublime/node_modules/tern/plugin** then it works.
If I run `npm install tern-jasmine` in the **tern_for_sublime** directory, the plugin does not work.

Debugging revealed the following:
* Tern loads **node_modules/tern-jasmine/jasmine.js** as it should
* This jasmine.js loads the **tern** and **infer** modules from its own node_modules/tern module instead of using the already-loaded tern module.
* Jasmine.js calls registerPlugin on the imported tern module but is never invoked again.

If I rename/remove tern-jasmine's **node-modules** folder, jasmine.js uses the parent node_modules path and registers itself correctly on the running tern instance.

Is my environment sane? Otherwise it should work if tern and acorn are only registered as devDependencies?

**Comment by angelozerr** [comment]
@tomv564 I have published a new version of tern-jasmine which uses now tern 0.15.0. I think it should work now.

**Comment by tomv564** [comment]
Thanks, works great now!
