### ISSUE TITLE
Usage? 

### ISSUE THREAD

**Issue by eshansingh** [angelozerr/tern-jasmine#4]
Can you add some info to the _README_ describing installation and usage steps?

**Comment by angelozerr** [comment]
* for installation, you can see https://github.com/angelozerr/tern-phaser and replace tern-phaser with tern-jasmine.
 * you can see screenshot at https://github.com/angelozerr/tern.java/wiki/Tern-&-Jasmine-support

**Comment by angelozerr** [comment]
I reopen issue to do that in this project

**Comment by angelozerr** [comment]
@eshansingh I have done maunual install. An interesting link is https://github.com/angelozerr/tern-jasmine#related-projects if you wish to use Protractor or Jasmine Matchers
